//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterManagement.BusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessCenterManagement.BusinessLogic.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists!.
        /// </summary>
        public static string AlreadyExistsMsg {
            get {
                return ResourceManager.GetString("AlreadyExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coefficient should be between 0 and 2!.
        /// </summary>
        public static string CoefficientBoundsMsg {
            get {
                return ResourceManager.GetString("CoefficientBoundsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be in the future!.
        /// </summary>
        public static string DateInTheFutureMsg {
            get {
                return ResourceManager.GetString("DateInTheFutureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be in the past!.
        /// </summary>
        public static string DateInThePastMsg {
            get {
                return ResourceManager.GetString("DateInThePastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Email is already taken!.
        /// </summary>
        public static string EmailIsTakenMsg {
            get {
                return ResourceManager.GetString("EmailIsTakenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be null!.
        /// </summary>
        public static string EmptyAddressMsg {
            get {
                return ResourceManager.GetString("EmptyAddressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be null!.
        /// </summary>
        public static string EmptyDescriptionMsg {
            get {
                return ResourceManager.GetString("EmptyDescriptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info cannot be null!.
        /// </summary>
        public static string EmptyInfoMsg {
            get {
                return ResourceManager.GetString("EmptyInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null!.
        /// </summary>
        public static string EmptyNameMsg {
            get {
                return ResourceManager.GetString("EmptyNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day is not correct!.
        /// </summary>
        public static string IncorrectDayOfWeekMsg {
            get {
                return ResourceManager.GetString("IncorrectDayOfWeekMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid profile info!.
        /// </summary>
        public static string InvalidProfileInfoMsg {
            get {
                return ResourceManager.GetString("InvalidProfileInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the meeting should be above less or 180!.
        /// </summary>
        public static string MaximumMinutesMsg {
            get {
                return ResourceManager.GetString("MaximumMinutesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor capacity should be above 0!.
        /// </summary>
        public static string MinVisitorCapacityMsg {
            get {
                return ResourceManager.GetString("MinVisitorCapacityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be unique!.
        /// </summary>
        public static string NameShouldBeUniqueMsg {
            get {
                return ResourceManager.GetString("NameShouldBeUniqueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of attendances should be above 0!.
        /// </summary>
        public static string NegativeAttendancesMsg {
            get {
                return ResourceManager.GetString("NegativeAttendancesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your balance can&apos;t be less than 0!.
        /// </summary>
        public static string NegativeBalance {
            get {
                return ResourceManager.GetString("NegativeBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost should be more or equal 0!.
        /// </summary>
        public static string NegativeCostMsg {
            get {
                return ResourceManager.GetString("NegativeCostMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of days should be above 0!.
        /// </summary>
        public static string NegativeDaysMsg {
            get {
                return ResourceManager.GetString("NegativeDaysMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the meeting should be above 0!.
        /// </summary>
        public static string NegativeMinutesMsg {
            get {
                return ResourceManager.GetString("NegativeMinutesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price should be above or equal 0!.
        /// </summary>
        public static string NegativePriceMsg {
            get {
                return ResourceManager.GetString("NegativePriceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of days for stop should be more or equal 0!.
        /// </summary>
        public static string NegativeStopDaysMsg {
            get {
                return ResourceManager.GetString("NegativeStopDaysMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visits count should be more or equal 0!.
        /// </summary>
        public static string NegativeVisitsCountMsg {
            get {
                return ResourceManager.GetString("NegativeVisitsCountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found!.
        /// </summary>
        public static string NotFoundMsg {
            get {
                return ResourceManager.GetString("NotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A venue should have a unique name for the address!.
        /// </summary>
        public static string NotUniqueAddressNameMsg {
            get {
                return ResourceManager.GetString("NotUniqueAddressNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity cannot be null!.
        /// </summary>
        public static string NullEntityMsg {
            get {
                return ResourceManager.GetString("NullEntityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text cannot be empty!.
        /// </summary>
        public static string NullTextMsg {
            get {
                return ResourceManager.GetString("NullTextMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate on null entity!.
        /// </summary>
        public static string OperateOnNullEntityMsg {
            get {
                return ResourceManager.GetString("OperateOnNullEntityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time you&apos;ve chosen is already taken.
        /// </summary>
        public static string TimeCrossesMsg {
            get {
                return ResourceManager.GetString("TimeCrossesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service should have a unique name for its specialization!.
        /// </summary>
        public static string UniqueNameForSpecialization {
            get {
                return ResourceManager.GetString("UniqueNameForSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of visits should be less than the one provided by the abonement!.
        /// </summary>
        public static string VisitsMoreThanAbonementAttendancesMsg {
            get {
                return ResourceManager.GetString("VisitsMoreThanAbonementAttendancesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day you&apos;ve chosen is not the one defined by the weekly event.
        /// </summary>
        public static string WrongDayOfWeekMsg {
            get {
                return ResourceManager.GetString("WrongDayOfWeekMsg", resourceCulture);
            }
        }
    }
}
