            // CreateMap<SpecializationModel, SpecializationDto>().ReverseMap()
            // CreateMap<ServiceModel, ServiceDto>().ReverseMap()
            // CreateMap<TrainerModel, TrainerDto>().ReverseMap()
            // CreateMap<TrainerEditModel, TrainerDto>().ReverseMap()
            // CreateMap<VenueModel, VenueDto>().ReverseMap()
            // CreateMap<EventModel, FitnessEventDto>().ReverseMap()
